openapi: 3.0.0
servers: []
info:
  description: This API provides Audit Info
  version: "1.0.0"
  title: Audit API
  contact:
    email: ksidhu123@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: clocking_system
    description: Operations available on clocking systems
paths:
  /reporting/clock-in:
    get:
        tags:
          - devices
        summary: gets a clock-in reading from history
        operationId: app.get_clock_in_reading
        description: Gets clock in readings from the event store
        parameters:
          - name: index
            in: query
            description: Gets a clock in at the index in the event store 
            schema:
              type: integer
              example: 100
        responses:
          '200':
            description: Successfully returned a clock in event
            content:
              application/json:
                schema:
                  type: object
                  items:
                    $ref: '#/components/schemas/checkin'
          '400':
            description: Invalid request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
          '404':
            description: Not found

  /reporting/clock-out:
    get:
      tags:
          - devices
      summary: gets a clock-out reading from history
      operationId: app.get_clock_out_reading
      description: Gets clock out readings from the event store
      parameters:
        - name: index
          in: query
          description: Gets a clock out at the index in the event store 
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Successfully returned a clock out event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/checkout'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not found

components:
  schemas:
    checkin:
      type: object
      required:
        - trace_id
        - emp_num
        - emp_name
        - store_code
        - num_hours_scheduled
        - timestamp
        - late_arrival
      properties:
        trace_id:
          type: string
          format: uuid
          example: 16fd2706-8baf-433b-82eb-8c7fada847da
        emp_num:
          type: string
          example: RB6805
        emp_name:
          type: string
          example: Amy
        store_code:
          type: string
          example: RB
        num_hours_scheduled:
          type: number
          example: 8
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        late_arrival:
          type: number
          example: 0.5
        
    checkout:
      type: object
      required:
        - trace_id
        - emp_num
        - emp_name
        - store_code
        - num_hours_worked
        - timestamp
        - overtime_hours
      properties:
        trace_id:
          type: string
          format: uuid
          example: 16fd2706-8baf-433b-82eb-8c7fada847da
        emp_num:
          type: string
          example: PK3555
        emp_name:
          type: string
          example: Amy
        store_code:
          type: string
          example: PK
        num_hours_worked:
          type: number
          example: 9
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        overtime_hours: 
          type: number
          example: 1.0
        